Repository sm-koeunseo/Smart-Farm-Hanni, pull requests merged in 2024-06, with the labels that each got.

#17 [PR] 12-feature/webserver
  webServer/main.py
  webServer/mysql.py
Labels: 은서 🐰, PR 🙌, flask 🔗

#19 [PR] 11-bug/soil huminity vaild value
  test/SoilMoisture/SoilMoisture3008/SoilMoistrue_multisensors.py
  test/SoilMoisture/SoilMoisture3008/SoilMoisture.py
  test/SoilMoisture/SoilMoisture3008/SoliMoistrue_value.txt
  test/SoilMoisture/SoilMoisture3208/SmartFarm.py
  test/SoilMoisture/SoilMoisture3208/SoilMoisture.py
  test/SoilMoisture/SoilMoisture3208/SoilMoisture2.py
  test/SoilMoisture/SoilMoisture3208/data1.txt
  test/SoilMoisture/SoilMoisture3208/gravity_soil.py
  test/SoilMoisture/SoilMoisture3208/icbanq.py
  test/SoilMoisture/SoilMoisture3208/icbanq_data.txt
Labels: bug 🐞, feature 💡, 은서 🐰, PR 🙌

#20 [PR] 5-soil humidity
  feature/SoilHumidity/test.py
  test/SoilMoisture/SoilMoisture3008/makefile.py
  test/SoilMoisture/SoilMoisture3008/makefile.txt
  test/SoilMoisture/SoilMoisture3008/soil_humidity_3.csv
  test/SoilMoisture/SoilMoisture3008/soil_humidity_3_2.csv
  test/SoilMoisture/SoilMoisture3008/soil_humidity_3_3.csv
  test/WaterPump.py
Labels: feature 💡, 은서 🐰, PR 🙌

#22 [PR] 21-feature/synthesis
  feature/feature.py
Labels: feature 💡, 은서 🐰, PR 🙌

#23 [PR] 3-feature/Temperature
  feature/Temperature/test.py
Labels: feature 💡, 민영 🐒, PR 🙌
